/* Generated By:JJTree: Do not edit this line. ASTAssignStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTAssignStmt extends SimpleNode {
  public ASTAssignStmt(int id) {
    super(id);
  }

  public ASTAssignStmt(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=96eb474c7a5326e9f5fcf2d9a74569a5 (do not edit this line) */
