/* Generated By:JJTree: Do not edit this line. ASTSwitchStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTSwitchStmt extends SimpleNode {
  public ASTSwitchStmt(int id) {
    super(id);
  }

  public ASTSwitchStmt(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=046633e54af73dc2f284909eac3a37fe (do not edit this line) */
