/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.2 */
package analyzer.ast;

public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTDECLARATION = 1;
  public int JJTBLOCK = 2;
  public int JJTSTMT = 3;
  public int JJTIFSTMT = 4;
  public int JJTWHILESTMT = 5;
  public int JJTASSIGNSTMT = 6;
  public int JJTEXPR = 7;
  public int JJTBOOLEXPR = 8;
  public int JJTCOMPEXPR = 9;
  public int JJTADDEXPR = 10;
  public int JJTMULEXPR = 11;
  public int JJTUNAEXPR = 12;
  public int JJTNOTEXPR = 13;
  public int JJTGENVALUE = 14;
  public int JJTBOOLVALUE = 15;
  public int JJTIDENTIFIER = 16;
  public int JJTINTVALUE = 17;
  public int JJTSWITCHSTMT = 18;
  public int JJTDEFAULTSTMT = 19;
  public int JJTCASESTMT = 20;


  public String[] jjtNodeName = {
    "Program",
    "Declaration",
    "Block",
    "Stmt",
    "IfStmt",
    "WhileStmt",
    "AssignStmt",
    "Expr",
    "BoolExpr",
    "CompExpr",
    "AddExpr",
    "MulExpr",
    "UnaExpr",
    "NotExpr",
    "GenValue",
    "BoolValue",
    "Identifier",
    "IntValue",
    "SwitchStmt",
    "DefaultStmt",
    "CaseStmt",
  };
}
/* JavaCC - OriginalChecksum=16bb7764c935ef29bd0e664ebbcc8c60 (do not edit this line) */
